{
	description = "NixOS gaming rig — Ryzen 9 7950X3D / RTX 4080 Super / AW3225QF HDR";

	inputs = {
		nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

		# Chaotic-Nyx: CachyOS kernel, proton-cachyos, bleeding-edge gaming packages.
		# Deliberately NOT doing `chaotic.inputs.nixpkgs.follows = "nixpkgs"`:
		# chaotic's binary cache is built against its own pinned nixpkgs revision,
		# so following ours would cause cache misses and local rebuilds.
		chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable";

		# Google Antigravity — agentic IDE (the editor) + `agy` terminal CLI.
		# Community flake that wraps Google's official tarballs in an FHS env;
		# auto-updates ~3x/week. NOT in nixpkgs — if it ever breaks a rebuild,
		# delete this input and the agyModule below and you're clean.
		antigravity-nix = {
			url = "github:jacopone/antigravity-nix";
			inputs.nixpkgs.follows = "nixpkgs";
		};
	};

	outputs = { nixpkgs, chaotic, antigravity-nix, ... }:
		let
			system = "x86_64-linux";

			# Google Antigravity (requires AES-NI — the 7950X3D has it)
			agyModule = {
				environment.systemPackages = with antigravity-nix.packages.${system}; [
					google-antigravity-cli  # `agy` in a terminal
					google-antigravity-ide  # the editor
					# default               # Antigravity 2.0 desktop agent — uncomment if wanted
				];
			};

			# Everything both targets share. Each machine keeps its own
			# hardware-configuration.nix (generated by that machine's installer).
			mkHost = extraModules: nixpkgs.lib.nixosSystem {
				inherit system;
				modules = [
					chaotic.nixosModules.default   # pulls in nyx binary cache + overlay + registry
					./configuration.nix
					agyModule
				] ++ extraModules;
			};
		in
		{
			nixosConfigurations = {
				# ── Bare metal (the real rig) ─────────────────────────────────────
				#   sudo nixos-rebuild switch --flake /etc/nixos#arrakis
				arrakis = mkHost [
					./hardware-configuration.nix
				];

				# ── Test VM (VMware Workstation on Windows) ───────────────────────
				#   sudo nixos-rebuild switch --flake /etc/nixos#arrakis-vm
				# Same config, but vm.nix replaces the NVIDIA stack with the VMware
				# guest driver. Inside the VM, /etc/nixos/hardware-configuration.nix
				# must be the one the VM's own installer generated.
				arrakis-vm = mkHost [
					./vm.nix
					./hardware-configuration.nix
				];
			};
		};
}
